### PR TITLE
Added keybinds and some more stuff

### PR DESCRIPTION
**Pull request by jaydamani**
- keybinds by lsp would be added whenever a language server is active.

- Added new keybinds for bufferline and keybinds for adding/deleting buffer.

- You can now autocomplete in insert mode using tab.

### CODE REVIEW

**Review by jaydamani — COMMENTED** [review]
This was an accidental commit and has been reverted.

**Comment by siduck76** [comment]
Im still novice at lua and I dont get some of the changes you made sorry , any previous features havent been removed right? and also whats the keybind for <S-l> capital S?

**Comment by siduck76** [comment]
> Im still novice at lua and I dont get some of the changes you made sorry , any previous features havent been removed right? and also whats the keybind for capital S? @jaydamani

**Comment by siduck76** [comment]
Thanks for the code refractoring!

**Pull request merged**
