### PR TITLE
add install script

### PR DESCRIPTION
**Pull request by jack0son**
Script to automatically symlink config, install packer, and chosen language servers.

### CODE REVIEW

**Comment by siduck76** [comment]
> Script to automatically symlink config, install packer, and chosen language servers.

since the config  supports html , css , the install script must have it mentioned under default langs

**Comment by jack0son** [comment]
> > Script to automatically symlink config, install packer, and chosen language servers.
> 
> since the config supports html and css , the install script must have it mentioned under default langs .

The default langs is for lsp dependencies rather than treesitter. Could add a treesitter config section as well.

**Comment by siduck76** [comment]
treesitter config is already provided so no need for that and besides html and css lsp dependencies are also required so it must be added .

**Comment by jack0son** [comment]
> treesitter config is already provided so no need for that and besides html and css lsp dependencies are also required so it must be added .

Okay makes sense.

**Pull request merged**
